### ISSUE TITLE
Add Tern (tern-for-vim)

### ISSUE THREAD

**Issue by deniskabana** [deniskabana/nzenvim#7]
https://github.com/ternjs/tern_for_vim
Tern lets you Jump to Definition, Find References and Rename variables.

Tern is awesome. It parses JS and adds options to auto-completion and it will play nice with these plugins:
- YouCompleteMe + JS definitions + Flow
- Needed for TagBar to work with JS
- Navigating, renaming and finding references/variables

**Comment by leonapoleon** [comment]
Needed for https://github.com/leonapoleon/vimrc/issues/5

**Comment by leonapoleon** [comment]
Needed for https://github.com/leonapoleon/vimrc/issues/8

**Comment by deniskabana** [comment]
Won't do - `ternjs` is no longer developed actively.
